### ISSUE TITLE
Airshipbot posting "The Change that closes this issue was merged." to airshipctl for treasuremap patchsets

### ISSUE THREAD

**Issue by eak13** [airshipit/gerrit-to-github-bot#2]
Airshipbot appears to be posting "The Change that closes this issue was merged." with the patchset to airshipctl issues when a treasuremap patchset merges. 

Take https://review.opendev.org/c/airship/treasuremap/+/787406/ as an example. The closed message went to https://github.com/airshipit/airshipctl/issues/123.

The treasuremap issue is being closed, but there should not also be an airshipctl post.

**Comment by sirajyasin** [comment]
The Zuul Job for update github issue in treasuremap is disabled in this PS (https://review.opendev.org/c/airship/treasuremap/+/788812)
However the BOT issue need to be resolved.

**Comment by sirajyasin** [comment]
The BOT issue also should be resolved now. We have disabled the old tokens to make sure there is no other old instance of BOT running in any individuals machine. There should not be any BOT running for treasuremap repo now. We will observe if there is any BOT activity on treasuremap repo for few days before enabling BOT for treasuremap.

**Comment by sirajyasin** [comment]
@ak3216 , After we disabled the zuul update github issue and removed old github tokens, I have not noticed any BOT action for treasuremap repository. So it might be safe to close this issue. We will enable the BOT for treasuremap this week and will observe it for somedays.

**Comment by eak13** [comment]
@sirajyasin sounds good. I'll close it out. Thanks!
